TodoMVC Example
thedodd/ybc pull request #12
Opened 2020-11-11 23:13 UTC by quinnjr

This pull request includes an example TodoMVC example for `ybc` based off of the one in the main `yew` repository, sans the use of the storage API.

The example fulfills showing off some of the components of `ybc` (Media, Columns, Button, Card), but needs some additional work with including Input.

Also, to note, the callbacks for `batch_callback` are currently not using the allowed `Option<Msg>` since this has not been released yet by `yew`. This would be something to fix once `yew` releases the change.

Finally, I didn't do a new tag for this pull request since nothing changed in the library itself. The examples can be included later down the line with another release.

## Contribution Checklist

- [x] Executed `cargo clippy` and `cargo fmt` on code.
- [ ] Updated `Cargo.toml` `version` field.
- [ ] Updated `CHANGELOG.md`.
- [ ] Updated Release page.

2020-11-12 03:24 UTC, thedodd commented
@quinnjr omg man, you are absolutely ledge sir! I'm going to give this an eye and get it merged ASAP. At a minimum, I will have time to get to this PR this weekend. 🎉

2020-11-12 04:04 UTC, thedodd requested changes
Outstanding contribution! Thank you. I add a few small suggestions. Let me know what you think. Hopefully they are all valid suggestions.

2020-11-12 04:04 UTC, thedodd commented on examples/todo-mvc/src/lib.rs
> +};
I am typically partial to just using `yew::prelude::*;`. Any reason not to just do that?

2020-11-12 04:04 UTC, thedodd commented on examples/todo-mvc/src/lib.rs
> +                })
Looks like this is something we will want to eventually add to `ybc::Input`. Want to pop a ticket so that we can track this?

2020-11-12 04:04 UTC, thedodd commented on examples/todo-mvc/src/state.rs
> +        entry.completed = !entry.completed;
```suggestion
        if let Some(entry) = self.entries.iter_mut().filter(|entry| filter.fits(entry)).nth(idx) {
            entry.completed = !entry.completed;
        }
```

Though the unwrap should never fail, this is just another way to help avoid the potential panic due to some future refactoring. Thoughts?

2020-11-12 04:04 UTC, thedodd commented on examples/todo-mvc/src/state.rs
> +        entry.editing = !entry.editing;
Same suggestion as above.

2020-11-12 04:04 UTC, thedodd commented on examples/todo-mvc/src/state.rs
> +            let entry = self.entries.iter_mut().filter(|entry| filter.fits(entry)).nth(idx).unwrap();
″ (same as above)

2020-11-12 04:04 UTC, thedodd commented on examples/todo-mvc/src/state.rs
> +        self.entries.remove(idx);
```suggestion
    pub fn remove(&mut self, filter_idx: usize) {
        let idx_opt = self
                .entries
                .iter()
                .enumerate()
                .filter(|&(_, entry)| self.filter.fits(entry))
                .map(|(idx, _)| idx)
                .nth(filter_idx);
        if let Some(idx) = idx_opt {
            self.entries.remove(idx);
        };
```

I do believe I am understanding what this algorithm is doing. Hopefully the name of the parameter being changed to `filter_idx` will help to clarify, and this also removes an allocation (... which obviously doesn't matter at all here ...).

Thoughts?

2020-11-12 13:51 UTC, quinnjr commented on examples/todo-mvc/src/lib.rs
> +};
No particular reason. I was mostly just following what was done in the example in the main `yew` repo. This can easily be changed.

2020-11-12 13:55 UTC, quinnjr commented on examples/todo-mvc/src/lib.rs
> +                })
I thought about that, and my response is a 'probably.' I just also worry about needing to constantly go back and add more properties as people (hopefully) pick up the library and expect more of the standard global attributes on these components. 

I'm thinking of writing a macro for doing so, but that's going to be slow work on my end with the end-of-the-year crunch now starting.

2023-02-15 18:28 UTC, thedodd commented
Giving a ping here. We've got a beta going on for the 0.4 release line. Happy to get this work merged, though it looks like there might be some outstanding work to be done. Hope all is well!

2023-02-21 16:15 UTC, quinnjr commented
I moved back to using Angular for projects. Not much interested in updating this.

2023-02-21 16:15 UTC, closed without merging