Feature make character of PaginationEllipsis configurable
thedodd/ybc pull request #38
Opened 2023-04-03 06:57 UTC by shenek

And set the default character to "…" instead of "&hellip;", because "&hellip;" was not displayed correctly with the latest version of yew.

Before:
![before](https://user-images.githubusercontent.com/2659336/229433403-5e8e3a92-ec09-4166-863e-68308af5f451.png)

After:
![after](https://user-images.githubusercontent.com/2659336/229433444-7fe05834-657a-4177-8e13-69fc3ef415de.png)

2023-04-11 18:31 UTC, thedodd commented on src/components/pagination.rs
> +///
Might be good to add a simple doc string here.

2023-04-11 18:32 UTC, thedodd requested changes
Thanks for the PR! One small thing.

2023-04-15 11:24 UTC, shenek commented
Very simple doc string added and I also updated changelog.

2023-04-18 16:00 UTC, thedodd approved these changes
🎉

2023-04-18 16:00 UTC, merged